Draw pen hover position into image
rien/reStream pull request #46
Opened 2021-01-15 21:41 UTC by lluchs

This is useful to point out parts of your drawing directly on remarkable when streaming to a video conference.

Demo:

https://user-images.githubusercontent.com/516527/104781158-44688e80-5782-11eb-8416-4a6d07bf36dc.mp4

I don't have a RM1, so I couldn't test there. I did implement two bytes per pixel, but inverting might work differently.

Adds a dependency on libremarkable for input handling.

2021-01-22 09:52 UTC, rien commented
Hi there!

This looks good, I didn't know this would be so easy. Do you notice an impact on framerate/lag? 

I'm planning on adding commandline features to reStream. so I'll merge this once that is implemented, with the option to turn this feature on/off.

Thanks!

2021-01-22 23:27 UTC, lluchs commented
>Do you notice an impact on framerate/lag?

I believe the framerate is currently only limited by the bandwidth of the USB link, so there's no impact from drawing the cursor. It does make the low framerate on more complex pages (that don't lz4-compress as well) very noticeable, though.

>I'm planning on adding commandline features to reStream. so I'll merge this once that is implemented, with the option to turn this feature on/off.

Excellent, I can update the PR once that's there.

2021-01-29 08:47 UTC, rien commented
@lluchs I've created a new release (with the addition of command line arguments), can you rebase your PR on it and add an option to enable this feature?

2021-01-29 22:26 UTC, lluchs reviewed
I rebased and added an option now. There's a few places that might need adjustments for RM1.

>I believe the framerate is currently only limited by the bandwidth of the USB link

That doesn't seem to be true by the way, I think I was confused by `top` output because of the idling second core. I think I'm going to try doing the compression with two threads...

2021-01-29 22:26 UTC, lluchs commented on Cargo.toml
> +libremarkable = "0.4.3"
This pulls in a lot of unnecessary dependencies, I already opened a PR (linked earlier) to reduce that somewhat. Doesn't seem to have an effect on binary size, though.

2021-01-29 22:26 UTC, lluchs commented on src/main.rs
> +        if let (false, Some((y, x))) = (self.drawing, self.pen_pos) {
The input and framebuffer axes are swapped on RM2, so we have `(y, x)` here. Might be different on RM1.

2021-01-29 22:26 UTC, lluchs commented on src/main.rs
> +                // TODO: Do something sensible on RM1
I don't know how the RM1 framebuffer works, inverting each byte like this might be wrong.

2022-05-07 17:53 UTC, abmantis commented
Are there any plans to get this merged?

2022-05-07 18:50 UTC, abmantis requested changes

2022-05-07 18:50 UTC, abmantis commented on src/main.rs
> +            let height = self.height as isize;
```suggestion
            let flip = self.width > self.height;
            let (x, y) = if flip { (y, x) } else { (x, y) };
            // we need negative numbers to calculate offsets correctly
            let width = if flip { self.height } else { self.width } as isize;
            let height = if flip { self.width } else { self.height } as isize;
```
A rm2 without rm2fb has inverted width/height

2022-05-07 18:50 UTC, abmantis commented on src/main.rs
> +            let height = self.height as isize;
With this change, it works nicely!

2022-05-09 07:56 UTC, rien commented
Hi @abmantis, I can look at merging this but I would first have to test if this works on an rM1.

You can create a new PR with the changes you requested, rebased with the current main branch.

2022-05-09 10:05 UTC, abmantis commented
> Hi @abmantis, I can look at merging this but I would first have to test if this works on an rM1.
> 
> You can create a new PR with the changes you requested, rebased with the current main branch.

I already had a working branch that was updated from the main branch already. Opened a PR now: #90 
I've only tested this on a rM2 (without rm2fb). If you are not able to get a rM1 to test, maybe it can be integrated anyway since it is not enabled by default, and someone can open an Issue or PR later if it does not work properly on rM1.

2023-10-08 19:33 UTC, abmantis commented
@rien  ever had the change to look at #90 ?

2024-01-09 16:53 UTC, merged